### ISSUE TITLE
close dont do anything

### ISSUE THREAD

**Issue by crisng95** [ambisign-gavin/react-native-swipe-item#1]

**Comment by ambisign-gavin** [comment]
I'm sorry, I don't know what do you mean exactly, could you please give me more information? thanks.

**Comment by masum-mollik** [comment]
close method does not work

**Comment by cinder92** [comment]
@masum-mollik @ambisign-gavin seems that `close` method only return `void`

**Comment by ambisign-gavin** [comment]
@cinder92  yes, the close method returns void.

@masum-mollik  so what you meant is that swipe item is not closed when you called the close method?
the close method is doing fine in my demo project, could you please give me some reproduce codes? or react and react-native version.

**Comment by saimonventura** [comment]
Can you show how I can click to close? I don't understand how call close method.

**Comment by saimonventura** [comment]
> Can you show how I can click to close? I don't understand how call close method.

```
const refItem = useRef();

refItem.current.close().


<SwipeItem ref={refItem}>
...
</SwipeItem>
```

**Comment by ambisign-gavin** [comment]
> > Can you show how I can click to close? I don't understand how call close method.
> 
> ```
> const refItem = useRef();
> 
> refItem.current.close().
> 
> 
> <SwipeItem ref={refItem}>
> ...
> </SwipeItem>
> ```

yes, that's  correct.

**Comment by Yunnathai** [comment]
same issues close not word in react-native typescript 

TypeError: undefined is not an object (evaluating '_this2$menuRef.current.close')
![image](https://user-images.githubusercontent.com/5283666/167283581-73c784eb-9656-4f9a-97a8-bc6f78dcc2f9.png)

![image](https://user-images.githubusercontent.com/5283666/167283574-83597c92-98a4-4aca-a508-efe8ef1b652a.png)
