### ISSUE TITLE
How to prevent swipe left when there are not leftButtons prop defined?

### ISSUE THREAD

**Issue by cinder92** [ambisign-gavin/react-native-swipe-item#2]
hello, thanks for this plugin, i just put, `rightButtons` prop, but SwipeItem is able to swipe left, how can i disabled this?

**Comment by ambisign-gavin** [comment]
For now, you can't. 
When I developed this plugin, I expected users can swipe freely even without buttons, but I guess you're right, the iOS native swipe items are not able to be swiped when there are no buttons.

I will support the disable feature recently.

**Comment by lucasgismondi** [comment]
Thanks for making this library! Yes would love for the ability to disable swiping left if there are no left buttons also

**Comment by ambisign-gavin** [comment]
@cinder92 @test-js  hi, the disable swipe feature was released at version 0.4.0. You can use the [disableSwipeIfNoButton](https://github.com/ambisign-gavin/react-native-swipe-item/blob/master/README.md#disableSwipeIfNoButton) prop to implement it.

Please try it, if there are any problems please let me know. Thanks.

**Comment by lucasgismondi** [comment]
works great thank you!
