### ISSUE TITLE
Support with FlatList component ?

### ISSUE THREAD

**Issue by dfabreguette** [ambisign-gavin/react-native-swipe-item#23]
Just a simple question, is it usable with FlatList component ?
If so, where does SwipeProvider fit ?

I tried this :
```javascript
<SwipeProvider>
  <FlatList
    renderItem={({ item }) => (
      <SwipeItem
        leftButtons={leftButton}
      >
        ...
      </SwipeItem>
    )}
  ></FlatList>
</SwipeProvider>
```

But it breaks FlatList features (refresh, infinite loading, ...), only the first row visible, even though swipe feature seems to work fine.
How am I supposed to integrate SwipeProvider with FlatList component ?

**Comment by dfabreguette** [comment]
Looks like the problem was due to something else in my setup. 
Everything now works fine with v6 and this structure using a FlatList.

**Comment by fukemy** [comment]
hi, how did u fixed this? Thanks

**Comment by fukemy** [comment]
@dfabreguette-ap i want to implement swipe to reply like whatsapp, the first problem is the swipe does not close automatically when release finger. Here is my layout:
```
return (
        <SwipeProvider
            mode='single'
            closeTrigger='onButtonShowed'>
            <ImageBackground
                // source={require('../../assets/link_light.png')}
                style={{
                    flex: 1,
                    backgroundColor: theme.navBackground,
                }}>
                <GiftedChat
                    text={text}
                    onInputTextChanged={setText}
                    ref={inputRef}
                />
            </ImageBackground>
        </SwipeProvider>
    )
```

Please help my problem. thanks

**Comment by dfabreguette** [comment]
@fukemy if you use a FlatList, you need to move your "SwipeProvider" component right on top of your FlatList.
Then use the SwipeItem component to wrap your row component.
I also would use something else then an ImageBackground component to display an image as a background of the row, it creates a complex tag structure added up to the SwipeItem component tag structure, which is already complex (you have a background view holding your buttons, and the row sliding right or left on top of it.
Try to simple your code at maximum and add things one by one to see which code chunk is causing the problem.
Hope it helps
