### ISSUE TITLE
trigger MovedToOrigin when release finger

### ISSUE THREAD

**Issue by fukemy** [ambisign-gavin/react-native-swipe-item#27]
Hi,  first thanks you very much for great and useful library, that's best library i found after 2 day stackoverflow + github search.

 I want to implement swipeToReply like ChatsApp, it's show a reply icon when swipe, then when release, it's swipe back to close reply icon and show quote to reply.
 
 So I want to trigger MovedToOrigin when release finger, please guide me how to do it? thanks

**Comment by ambisign-gavin** [comment]
you can try this
```
...
const swipeItemRef = React.useRef();
...
<SwipeProvider>
    <SwipeItem
        ref={swipeItemRef}
        onLeftButtonsShowed={() => {
            setTimeout(() => swipeItemRef.current?.close(), 0);
        }}
        .....
    >
        <Text style={styles.text}>Swipe me!</Text>
    </SwipeItem>
</SwipeProvider>
```
Please remember to use `setTimeout`, because the swpie item is still acting while the ButtonsShowed event is triggered.

if this solution is not working for you, please feel free to let me know.

**Comment by fukemy** [comment]
Hi, im using GiftedChat for develop chat app, in screen i have a flatList, i did modify code like u guide but it's not working

**Comment by ambisign-gavin** [comment]
Hi, is the close function not working only in the onLeftButtonShowed and working correctly in other places?

**Comment by fukemy** [comment]
ok. I did this, the. problem is im assigned wrong ref into swipeItem
