### ISSUE TITLE
React-Native 0.62 - Animated.event

### ISSUE THREAD

**Issue by saimonventura** [ambisign-gavin/react-native-swipe-item#8]
Animated.event now requires a second argument for options

**Comment by osamasaeedaltafseer** [comment]
same issue

**Comment by vtn-dev-sameer** [comment]
same issue

**Comment by vtn-dev-sameer** [comment]
please replace 
Animated.event([null,{dx:this.state.panDistance.x}]),
with
Animated.event([null,{dx:this.state.panDistance.x}],{useNativeDriver: true}),

in node_modules/react-native-swipe-item/dist/component/swipeItem.js

**Comment by MbIWaTUK** [comment]
same issue

**Comment by ambisign-gavin** [comment]
https://github.com/ambisign-gavin/react-native-swipe-item/commit/05f767ce9ef9ce799274656c33dca52e963cd226 fixed the problem.
